ProyectoRRHH/Models/ReciboSueldo.cs
using System.ComponentModel.DataAnnotations;

namespace ProyectoRRHH.Models
{
    public class ReciboSueldo
    {

        public Guid Id { get; set; }


        [DataType(DataType.Date)]
        [Required(ErrorMessage = "La fecha de cobro es obligatoria.")]
        public DateTime FechaCobro { get; set; }


        [Range(0, double.MaxValue, ErrorMessage = "El sueldo bruto no puede ser negativo.")]
        public double SueldoBruto { get; set; }


        public string UsuarioDni { get; set; }


        public Usuario Usuario { get; set; }


        public bool Firmado { get; set; }


        public double SueldoNeto => SueldoBruto * (1 - Constantes.Descuento);
        public double Jubilacion => SueldoBruto * (Constantes.DescuentoJubilacion);
        public double ObraSocial => SueldoBruto * (Constantes.DescuentoObraSocial);
        public double Ley19032 => SueldoBruto * (Constantes.DescuentoLey);
    }

    public static class Constantes
    {
        public const double Descuento = 0.17; // Descuento total

        public const double DescuentoJubilacion = 0.11; // 11% descuento jubilacion

        public const double DescuentoObraSocial = 0.03; // 3% descuento obra social

        public const double DescuentoLey = 0.03; // 3% descuento ley 19032
    }
}

ProyectoRRHH/Controllers/ReciboSueldoController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoRRHH.Context;
using ProyectoRRHH.Models;
using System.Security.Claims;
using Microsoft.CodeAnalysis.Elfie.Serialization;

public class ReciboSueldoController : Controller
{
    private readonly EmpresaDatabaseContext _context;

    public ReciboSueldoController(EmpresaDatabaseContext context)
    {
        _context = context;
    }

    // GET: ReciboSueldoes
    public async Task<IActionResult> Index(string buscar, string filtro)
    {
        // Persistir parámetros en ViewData
        ViewData["Buscar"] = buscar;

        // Obtener el DNI del usuario logueado
        var usuarioDni = User.FindFirstValue("Dni");

        if (User.IsInRole("Empleado"))
        {
            // Filtrar los recibos solo para el usuario logueado
            var recibos = await _context.ReciboSueldos
                                        .Where(r => r.UsuarioDni == usuarioDni)
                                        .Include(r => r.Usuario)
                                        .ToListAsync();

            // Pasar el DNI a la vista
            ViewBag.UsuarioDni = usuarioDni;

            return View(recibos);
        }
        else if (User.IsInRole("Administrador"))
        {
            // Obtener todos los recibos
            var recibos = _context.ReciboSueldos.Include(r => r.Usuario).AsQueryable();

            // Aplicar búsqueda si es necesario
            if (!string.IsNullOrEmpty(buscar))
            {
                recibos = recibos.Where(s => s.UsuarioDni.Contains(buscar));
            }

            // Establecer el filtro de ordenación (alternar entre "DniAscendente" y "DniDescendente")
            if (string.IsNullOrEmpty(filtro))
            {
                filtro = "DniAscendente"; // Valor por defecto si no se pasa filtro
            }

            // Alternar entre ascendente y descendente
            ViewData["FiltroDni"] = filtro == "DniAscendente" ? "DniDescendente" : "DniAscendente";

            // Aplicar orden según el filtro
            switch (filtro)
            {
                case "DniDescendente":
                    recibos = recibos.OrderByDescending(r => r.UsuarioDni);
                    break;

                case "DniAscendente":
                default:
                    recibos = recibos.OrderBy(r => r.UsuarioDni);
                    break;
            }

            // Convertir a lista y devolver
            var listaRecibos = await recibos.ToListAsync();
            return View(listaRecibos);
        }
        else
        {
            // Si el usuario no tiene el rol adecuado
            return Unauthorized();
        }
    }
    // GET: ReciboSueldoes/Details/5
    public async Task<IActionResult> Details(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var reciboSueldo = await _context.ReciboSueldos
            .Include(r => r.Usuario)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (reciboSueldo == null)
        {
            return NotFound();
        }

        return View(reciboSueldo);
    }

    // GET: ReciboSueldoes/Create
    public IActionResult Create()
    {
        // Lista de DNI para el dropdown
        ViewData["UsuarioDni"] = new SelectList(_context.Usuarios, "Dni", "Dni");

        // Diccionario con la información de los usuarios: DNI como clave y "Nombre Apellido" como valor
        ViewBag.UsuariosInfo = _context.Usuarios
            .Select(u => new { u.Dni, NombreCompleto = $"{u.Nombre} {u.Apellido}" })
            .ToDictionary(u => u.Dni, u => u.NombreCompleto);

        return View();
    }

    // POST: ReciboSueldoes/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,FechaCobro,SueldoBruto,UsuarioDni")] ReciboSueldo reciboSueldo)
    {
        if (ModelState.IsValid)
        {
            reciboSueldo.Id = Guid.NewGuid();
            reciboSueldo.SueldoBruto = reciboSueldo.SueldoBruto;
            _context.Add(reciboSueldo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        ViewData["UsuarioDni"] = new SelectList(_context.Usuarios, "Dni", "Dni", reciboSueldo.UsuarioDni);
        return View(reciboSueldo);
    }

    // GET: ReciboSueldoes/Edit/5
    public async Task<IActionResult> Edit(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var reciboSueldo = await _context.ReciboSueldos.FindAsync(id);
        if (reciboSueldo == null)
        {
            return NotFound();
        }
        ViewData["UsuarioDni"] = new SelectList(_context.Usuarios, "Dni", "Dni", reciboSueldo.UsuarioDni);
        return View(reciboSueldo);
    }

    // POST: ReciboSueldoes/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, [Bind("Id,FechaCobro,SueldoBruto,UsuarioDni")] ReciboSueldo reciboSueldo)
    {
        if (id != reciboSueldo.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(reciboSueldo);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ReciboSueldoExists(reciboSueldo.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        ViewData["UsuarioDni"] = new SelectList(_context.Usuarios, "Dni", "Dni", reciboSueldo.UsuarioDni);
        return View(reciboSueldo);
    }

    // GET: ReciboSueldoes/Delete/5
    public async Task<IActionResult> Delete(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var reciboSueldo = await _context.ReciboSueldos
            .Include(r => r.Usuario)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (reciboSueldo == null)
        {
            return NotFound();
        }

        return View(reciboSueldo);
    }

    // POST: ReciboSueldoes/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
        var reciboSueldo = await _context.ReciboSueldos.FindAsync(id);
        if (reciboSueldo != null)
        {
            _context.ReciboSueldos.Remove(reciboSueldo);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Firmar(Guid id)
    {
        // Obtener el recibo
        var recibo = await _context.ReciboSueldos.FindAsync(id);

        if (recibo == null)
        {
            return NotFound();
        }

        // Verificar que el recibo pertenece al usuario logueado
        var usuarioDni = User.FindFirstValue("Dni");
        if (recibo.UsuarioDni != usuarioDni)
        {
            return Unauthorized();
        }

        // Verificar si ya está firmado
        if (recibo.Firmado)
        {
            return BadRequest("El recibo ya está firmado.");
        }

        // Marcar el recibo como firmado
        recibo.Firmado = true;

        _context.Update(recibo);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    private bool ReciboSueldoExists(Guid id)
    {
        return _context.ReciboSueldos.Any(e => e.Id == id);
    }

    [HttpGet]
    public IActionResult GetById(string id)
    {
        Guid idGuid = new Guid(id);
        var obj = _context.ReciboSueldos
       .Include(r => r.Usuario) // Eagerly load the Usuario navigation property
       .FirstOrDefault(r => r.Id == idGuid);
        if (obj == null)
        {
            return NotFound();
        }
        var result = new
        {
            obj.FechaCobro,
            obj.SueldoNeto,
            obj.SueldoBruto,
            obj.UsuarioDni,
            obj.Usuario.NombreCompleto
        };
        return Json(result); // Return the object as JSON
    }
}

ProyectoRRHH/Views/ReciboSueldo/Create.cshtml
@model ProyectoRRHH.Models.ReciboSueldo

@{
    ViewData["Title"] = "Create";
}

<h1>Generar Recibo de Sueldo</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!-- Selección de Usuario (DNI) -->
            <div class="form-group">
                <label asp-for="UsuarioDni" class="control-label">DNI</label>
                <select asp-for="UsuarioDni" class="form-control" asp-items="ViewBag.UsuarioDni" id="usuarioDni"></select>
            </div>

            <!-- Campo para mostrar Nombre y Apellido -->
            <div class="form-group">
                <label for="nombreCompleto" class="control-label">Nombre Completo</label>
                <input id="nombreCompleto" class="form-control" type="text" readonly />
            </div>

            <!-- Fecha de Cobro -->
            <div class="form-group">
                <label asp-for="FechaCobro" class="control-label">Fecha de Cobro</label>
                <input asp-for="FechaCobro" class="form-control" />
                <span asp-validation-for="FechaCobro" class="text-danger"></span>
            </div>

            <!-- Sueldo Bruto -->
            <div class="form-group">
                <label asp-for="SueldoBruto" class="control-label">Sueldo Bruto</label>
                <input asp-for="SueldoBruto" class="form-control" />
                <span asp-validation-for="SueldoBruto" class="text-danger"></span>
            </div>

            <div class="form-group mt-3">
                <input type="submit" value="Generar" class="btn btn-success" />
                <a asp-controller="ReciboSueldo" asp-action="Index" class="btn btn-outline-success">Ver Listado</a>
                <a asp-controller="Home" asp-action="Index" class="btn btn-outline-danger">Volver atrás</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <!-- Incluye los scripts de validación -->
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <!-- Lógica para mostrar Nombre Completo -->
    <script>
        // Obtener el diccionario desde el ViewBag
        const usuariosInfo = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.UsuariosInfo));

        // Referencia al dropdown de DNI y al campo de texto de Nombre Completo
        const usuarioDniDropdown = document.getElementById("usuarioDni");
        const nombreCompletoInput = document.getElementById("nombreCompleto");

        // Evento para cambiar el nombre completo al seleccionar un DNI
        usuarioDniDropdown.addEventListener("change", () => {
            const selectedDni = usuarioDniDropdown.value;
            if (usuariosInfo[selectedDni]) {
                nombreCompletoInput.value = usuariosInfo[selectedDni];
            } else {
                nombreCompletoInput.value = "";
            }
        });
    </script>
}

ProyectoRRHH/Views/ReciboSueldo/Delete.cshtml
@model ProyectoRRHH.Models.ReciboSueldo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ReciboSueldo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaCobro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaCobro)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.sueldo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sueldo)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Dni)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-outline-danger">Volver Atrás</a>
    </form>
</div>

ProyectoRRHH/Views/ReciboSueldo/Details.cshtml
@model ProyectoRRHH.Models.ReciboSueldo

@{
    ViewData["Title"] = "Details";
}

<div class="printable">
    <h1>Detalles del recibo</h1>
    <div>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.FechaCobro)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.FechaCobro)
            </dd>
            @*<dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.sueldo)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.sueldo)
            </dd>*@
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Usuario)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Usuario.Dni)
            </dd>
        </dl>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-outline-success">Editar</a>
    <button onclick="printPage()" class="btn btn-outline-primary">Imprimir recibo</button>|
    <a class="btn btn-outline-danger" asp-action="Index">Volver atrás</a>
</div>

ProyectoRRHH/Views/ReciboSueldo/Edit.cshtml
@model ProyectoRRHH.Models.ReciboSueldo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ReciboSueldo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FechaCobro" class="control-label"></label>
                <input asp-for="FechaCobro" class="form-control" />
                <span asp-validation-for="FechaCobro" class="text-danger"></span>
            </div>
            @*@<div class="form-group">
                <label asp-for="sueldo" class="control-label"></label>
                <input asp-for="sueldo" class="form-control" />
                <span asp-validation-for="sueldo" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="UsuarioDni" class="control-label"></label>
                <select asp-for="UsuarioDni" class="form-control" asp-items="ViewBag.UsuarioDni"></select>
                <span asp-validation-for="UsuarioDni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-danger">Volver atrás</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProyectoRRHH/Views/ReciboSueldo/Index.cshtml
@model IEnumerable<ProyectoRRHH.Models.ReciboSueldo>

@{
    ViewData["Title"] = "Index";
}
<div class="w-100 hide-print">

    <h1>Recibos de Sueldo</h1>

    @if (User.IsInRole("Administrador"))

    {
        <form asp-action="Index" method="get">
            <div class="form-group">
                <input type="text" name="buscar" class="form-control" placeholder="Buscar por DNI" value="@ViewData["buscar"]" />
            </div>
            <button type="submit" class="btn btn-primary w-100 mt-3">Buscar</button>
        </form>

    }

    <table class="table table-striped table-hover w-100">
        <thead>
            <tr>
                <th>
                @if (User.IsInRole("Administrador")) // Solo el Administrador puede ordenar por DNI
                {
                    <a asp-action="Index" asp-route-filtro="@ViewData["FiltroDni"]">
                        DNI
                    </a>
                }
                else
                {
                    <span>DNI</span>
                }
                </th>
                <th>Fecha de Cobro</th>
                <th>Sueldo Bruto</th>
                <th>Descuento Jubilación</th>
                <th>Descuento Obra Social</th>
                <th>Descuento Ley 19032</th>
                <th>Total Descuentos</th>
                <th>Sueldo Neto</th>
                <th>Firma</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var recibo in Model)

            {
                <tr>
                    <td>@recibo.UsuarioDni.ToString()</td>
                    <td>@recibo.FechaCobro.ToShortDateString()</td>
                    <td>@recibo.SueldoBruto.ToString("C")</td>
                    <td>@recibo.Jubilacion.ToString("C")</td>
                    <td>@recibo.ObraSocial.ToString("C")</td>
                    <td>@recibo.Ley19032.ToString("C")</td>
                    <td>
                        @((recibo.Jubilacion + recibo.ObraSocial + recibo.Ley19032).ToString("C"))
                    </td>
                    <td>@recibo.SueldoNeto.ToString("C")</td>
                    @if (recibo.Firmado)
                    {
                        <td>
                            <div class="d-flex w-100 flex-column">
                                <span>Firmado</span>
                                <button class="btn btn-outline-success" onclick="printThisRecibo('@recibo.Id')">Imprimir</button>
                            </div>
                        </td>
                    }
                    else if (!recibo.Firmado && User.IsInRole("Administrador"))
                    {
                        <td>No Firmado</td>
                    }
                    else
                    {
                        <td>
                            <form asp-action="Firmar" method="post">
                                <input type="hidden" name="id" value="@recibo.Id" />
                                <button type="submit" class="btn btn-primary">Firmar Recibo</button>
                            </form>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="printable">
    <h1>Detalles del recibo</h1>
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Fecha de cobro
            </dt>
            <dd class="col-sm-10" id="printable-fechacobro">
                
            </dd>
            <dt class = "col-sm-2">
             Sueldo bruto
            </dt>
            <dd class="col-sm-10" id="printable-sueldobruto">
            </dd>
            <dt class="col-sm-2">
                Sueldo neto
            </dt>
            <dd class="col-sm-10" id="printable-sueldoneto">
            </dd>
            <dt class="col-sm-2">
                DNI
            </dt>
            <dd class="col-sm-10" id="printable-dni">
                
            </dd>
            <dt class="col-sm-2">
                Nombre completo
            </dt>
            <dd class="col-sm-10" id="printable-nombrecompleto">
                
            </dd>
        </dl>
    </div>
</div>

<script>
    async function printThisRecibo(idRecibo)
    {
        try
         {
                const response = await fetch(`/ReciboSueldo/GetById?id=${idRecibo}`);
                if (!response.ok) {
                    throw new Error('Error de conexión con la base de datos.');
                }
                const data = await response.json();
                console.log(data);
                document.getElementById("printable-fechacobro").innerHTML = data.fechaCobro;
                document.getElementById("printable-sueldobruto").innerHTML = data.sueldoBruto;
                document.getElementById("printable-sueldoneto").innerHTML = data.sueldoNeto;
                document.getElementById("printable-dni").innerHTML = data.usuarioDni;
                document.getElementById("printable-nombrecompleto").innerHTML = data.nombreCompleto;
                printPage();
            }
            catch (error) {
                console.error('ERROR: ', error);
            }
    }
</script>

@if (User.IsInRole("Empleado")) 

{
    <a asp-controller="Home" asp-action="Index" class="btn btn-outline-danger hide-print" mt-3">Volver atrás</a>
}

@if (User.IsInRole("Administrador")) 

{
    <a asp-action="Create" class="btn btn-outline-danger hide-print" mt-3">Volver atrás</a>
}