ProyectoRRHH/Controllers/LicenciaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using Microsoft.EntityFrameworkCore;
using ProyectoRRHH.Context;
using ProyectoRRHH.Models;

namespace ProyectoRRHH.Controllers
{
    public class LicenciaController : Controller
    {
        private readonly EmpresaDatabaseContext _context;

        public LicenciaController(EmpresaDatabaseContext context)
        {
            _context = context;
        }

        // GET: Licencia
        public async Task<IActionResult> Index(string buscar, string filtro)
        {
            // Persistir parámetros en ViewData
            ViewData["Buscar"] = buscar;
            // Obtener el DNI del usuario logueado
            var usuarioDni = User.FindFirstValue("Dni");
            if (User.IsInRole("Empleado"))
            {
                // Filtrar las licencias solo para el usuario logueado
                var licencias = await _context.Licencias
                                            .Where(l => l.UsuarioDni == usuarioDni)
                                            .Include(l => l.Usuario)
                                            .ToListAsync();

                // Pasar el DNI a la vista
                ViewBag.UsuarioDni = usuarioDni;

                return View(licencias);
            }
            else if (User.IsInRole("Administrador"))
            {
                var licencias = _context.Licencias.Include(l => l.Usuario).AsQueryable();

                if (!string.IsNullOrEmpty(buscar))
                {
                    licencias = licencias.Where(s => new[] { s.Usuario.Nombre, s.Usuario.Apellido }.Any(a => a.Contains(buscar)));
                }

                if (string.IsNullOrEmpty(filtro))
                {
                    filtro = "FechaIniDescendente"; // Valor por defecto si no se pasa filtro
                }

                ViewData["FiltroNombre"] = filtro == "NombreAscendente" ? "NombreDescendente" : "NombreAscendente";
                ViewData["FiltroEstado"] = filtro == "EstadoAscendente" ? "EstadoDescendente" : "EstadoAscendente";
                ViewData["FiltroFechaIni"] = filtro == "FechaIniAscendente" ? "FechaIniDescendente" : "FechaIniAscendente";

                switch (filtro)
                {
                    case "NombreDescendente":
                        licencias = licencias.OrderByDescending(licencia => licencia.Usuario.Nombre);
                        break;
                    case "FechaIniDescendente":
                        licencias = licencias.OrderByDescending(licencia => licencia.FechaInicio);
                        break;
                    case "FechaIniAscendente":
                        licencias = licencias.OrderBy(licencia => licencia.FechaInicio);
                        break;
                    case "EstadoDescendente":
                        licencias = licencias.OrderByDescending(licencia => licencia.Aprobado);
                        break;
                    case "EstadoAscendente":
                        licencias = licencias.OrderBy(licencia => licencia.Aprobado);
                        break;
                    default:
                        licencias = licencias.OrderBy(licencia => licencia.Usuario.Nombre);
                        break;
                }

                // Convertir a lista y devolver
                var listaLicencias = await licencias.ToListAsync();
                return View(licencias);
            }
            else
            {
                // Si el usuario no tiene el rol adecuado
                return Unauthorized();
            }
        }

        // GET: Licencia/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var licencia = await _context.Licencias
                .Include(l => l.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (licencia == null)
            {
                return NotFound();
            }

            return View(licencia);
        }

        // GET: Licencia/Create
        public IActionResult Create()
        {
            // Lista de DNI para el dropdown
            //ViewData["UsuarioDni"] = new SelectList(_context.Usuarios, "Dni", "Dni");
            
            if(User.IsInRole("Empleado"))
            {
                var usuarioDni = User.FindFirstValue("Dni");
                // Pasar el DNI a la vista
                var nombreCompleto = User.FindFirstValue("Nombre") + " " + User.FindFirstValue("Apellido");
                Usuario u = _context.Usuarios.FirstOrDefault(u => u.Dni == usuarioDni);
                ViewBag.UsuarioDni = usuarioDni;
                ViewBag.NombreCompleto = u.Nombre + " " + u.Apellido;
            }

            if(User.IsInRole("Administrador"))
            {
                // Lista de DNI para el dropdown
                ViewData["UsuarioDni"] = new SelectList(_context.Usuarios, "Dni", "Dni");

                // Diccionario con la información de los usuarios: DNI como clave y "Nombre Apellido" como valor
                ViewBag.UsuariosInfo = _context.Usuarios
                    .Select(u => new { u.Dni, NombreCompleto = $"{u.Nombre} {u.Apellido}" })
                    .ToDictionary(u => u.Dni, u => u.NombreCompleto);
            }
            return View();
        }

        public IActionResult SetAprobadoTrue(Guid? id)
        {
            var licencia = _context.Licencias.Find(id);
            if (licencia != null)
            {
                licencia.Aprobado = true;
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult SetAprobadoFalse(Guid? id)
        {
            var licencia = _context.Licencias.Find(id);
            if (licencia != null)
            {
                licencia.Aprobado = false;
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RevertAprobado(Guid? id)
        {
            var licencia = _context.Licencias.Find(id);
            if (licencia != null)
            {
                licencia.Aprobado = null;
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Licencia/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FechaInicio,CantDias,UsuarioDni,Aprobado")] Licencia licencia)
        {
            
            if(User.IsInRole("Administrador"))
            {
                // Que sea falso el Aprobado null, ya que si está marcado devuelve true, sino, null por Licencia/Create
                if (licencia.Aprobado == null)
                    licencia.Aprobado = false;
            }
            if (ModelState.IsValid)
            {
                licencia.Id = Guid.NewGuid();
                _context.Add(licencia);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UsuarioDni"] = new SelectList(_context.Usuarios, "Dni", "Dni", licencia.UsuarioDni);
            return View(licencia);
        }



        // GET: Licencia/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var licencia = await _context.Licencias.FindAsync(id);
            if (licencia == null)
            {
                return NotFound();
            }
            ViewData["UsuarioDni"] = new SelectList(_context.Usuarios, "Dni", "Dni", licencia.UsuarioDni);
            return View(licencia);
        }

        // POST: Licencia/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,FechaInicio,CantDias,UsuarioDni,Aprobado")] Licencia licencia)
        {
            if (id != licencia.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(licencia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LicenciaExists(licencia.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UsuarioDni"] = new SelectList(_context.Usuarios, "Dni", "Dni", licencia.UsuarioDni);
            return View(licencia);
        }

        // GET: Licencia/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var licencia = await _context.Licencias
                .Include(l => l.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (licencia == null)
            {
                return NotFound();
            }

            return View(licencia);
        }

        // POST: Licencia/Delete/5

ProyectoRRHH/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;

<!DOCTYPE html>
<html lang="es">
<head>
    <!--<meta charset="utf-8" />-->
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoRRHH</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoRRHH.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <!--Logo del menú-->
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" class="d-flex">
                    <div class="mx-auto d-flex justify-content-center logo-nb">
                        <svg id="logo-89" width="20" height="20" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><path class="ccustom" d="M39.9449 21.4998H32.8003C26.5594 21.4998 21.5003 26.559 21.5003 32.7998V39.9444C31.3502 39.214 39.2145 31.3497 39.9449 21.4998Z" fill="#775732"></path><path class="ccustom" d="M18.5003 39.9444V32.7998C18.5003 26.559 13.4411 21.4998 7.20026 21.4998H0.0556641C0.785998 31.3497 8.65036 39.214 18.5003 39.9444Z" fill="#775732"></path><path class="ccustom" d="M39.9449 18.4998C39.2145 8.64987 31.3502 0.78551 21.5003 0.0551758V7.19977C21.5003 13.4406 26.5594 18.4998 32.8003 18.4998H39.9449Z" fill="#775732"></path><path class="ccustom" d="M18.5003 0.0551758C8.65036 0.78551 0.785998 8.64987 0.0556641 18.4998H7.20026C13.4411 18.4998 18.5003 13.4406 18.5003 7.19977V0.0551758Z" fill="#775732"></path><path class="ccustom" d="M13.583 19.9998C16.3555 18.6145 18.615 16.355 20.0002 13.5825C21.3855 16.355 23.6449 18.6145 26.4175 19.9998C23.6449 21.385 21.3855 23.6445 20.0002 26.417C18.615 23.6445 16.3555 21.385 13.583 19.9998Z" fill="#CA9352"></path></svg>
                    </div>
                    ProyectoRRHH
                </a>
                <!--Items-->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                            @if (User.IsInRole("Administrador"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Create">Gestion de Empleados</a>
                                
                                </li>
                            }
                        

                        @*{
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AltaEmpleados">AltaEmpleados</a>

                        </li>
                        }*@

                        @if (User.IsInRole("Administrador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ReciboSueldo" asp-action="Create">Generar Recibos</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Licencia" asp-action="Index">Lista de licencias</a>
                            </li>
                        }
                        
                        @if (User.IsInRole("Empleado"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ReciboSueldo" asp-action="Index">Ver Mis Recibos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Licencia" asp-action="Index">Mis licencias</a>
                            </li>
                        }
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Acceso" asp-action="Salir">Salir</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        function printPage() {
            window.print();
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>